### ISSUE TITLE
ImportError: No module named innodb

### ISSUE THREAD

**Issue by kevinbin** [lefred/mysqlshell-plugins#1]
2019-10-12 10:27:21: Error: Error loading Python file '/Users/hongbin/.mysqlsh/plugins/ext/innodb/init.py':
        Execution failed:
Traceback (most recent call last):
  File "init.py", line 6, in <module>
ImportError: No module named innodb

2019-10-12 10:27:21: Error: Error loading Python file '/Users/hongbin/.mysqlsh/plugins/ext/router/init.py':
        Execution failed:
Traceback (most recent call last):
  File "init.py", line 5, in <module>
  File "/Users/hongbin/.mysqlsh/plugins/ext/router/status.py", line 2, in <module>
    import requests
ImportError: No module named requests

**Comment by lefred** [comment]
For "requests", you need to install python3-requests on your system (by dnf, yum, pip3, ...)

**Comment by kevinbin** [comment]
my python using brew install 

hongbin@MBP /u/l/opt> pip list |grep request
requests           2.20.1
hongbin@MBP /u/l/opt> ll /usr/local/opt/python/libexec/bin/pip
/usr/local/opt/python/libexec/bin/pip -> ../../bin/pip3

why mysqlsh not found ?

**Comment by lefred** [comment]
Sorry, with the actual version of MySQL Shell, could you try to install request for Python 2 ?

**Comment by lefred** [comment]
No more feedback, closing the issue
