### ISSUE TITLE
No module named '_crypt' on Windows

### ISSUE THREAD

**Issue by yrfu** [lefred/mysqlshell-plugins#37]
I was attempting MySQL Router REST API on Windows based on slide 24 of https://www.slideshare.net/lefred.descamps/mysql-router-rest-api

The error I received was as follows:
 MySQL  JS > \py
Switching to Python mode...
 MySQL  Py > import crypt
Traceback (most recent call last):
  File "C:\Program Files\MySQL\MySQL Shell 8.0\lib\Python3.9\lib\crypt.py", line 6, in <module>
    import _crypt
ModuleNotFoundError: No module named '_crypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\MySQL\MySQL Shell 8.0\lib\Python3.9\lib\crypt.py", line 9, in <module>
    raise ImportError("The crypt module is not supported on Windows")
ImportError: The crypt module is not supported on Windows

The following was also emitted in mysqlsh.log:
2022-02-23 01:14:34: Warning: Found errors loading plugins, for more details look at the log at: %APPDATA%\MySQL\mysqlsh\mysqlsh.log
2022-02-23 01:23:32: Info: Using credential store helper: C:\Program Files\MySQL\MySQL Shell 8.0\bin\mysql-secret-store-windows-credential.exe
2022-02-23 01:23:32: Info: Setting Python home to 'C:\Program Files\MySQL\MySQL Shell 8.0\lib\Python3.9'
2022-02-23 01:23:32: Info: Loading startup files...
2022-02-23 01:23:32: Info: Loading plugins...
2022-02-23 01:23:32: Error: Error loading Python file '%APPDATA%\MySQL\mysqlsh\plugins\router\init.py':
	Execution failed: 
Traceback (most recent call last):
  File "C:\Program Files\MySQL\MySQL Shell 8.0\lib\Python3.9\lib\crypt.py", line 6, in <module>
    import _crypt
ModuleNotFoundError: No module named '_crypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "init.py", line 5, in <module>
  File "C:\Program Files\MySQL\MySQL Shell 8.0\lib\Python3.9\lib\crypt.py", line 9, in <module>
    raise ImportError("The crypt module is not supported on Windows")
ImportError: The crypt module is not supported on Windows

**Comment by lefred** [comment]
Thank you for reporting this issue, however I don't have a solution for it right now.

**Comment by lefred** [comment]
Maybe I should try with bcrypt module ?

**Comment by AmiasLi** [comment]
Why do you need crypt. There is no such module like crypt in windows

**Comment by lefred** [comment]
did you try it ? that module is not required anymore since a long time

**Comment by AmiasLi** [comment]
haha. yeah, I know it. I just let the guy submitted the issue know the crypt is only available in linux
